/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practicahilos;

import java.awt.Font;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.SwingConstants;

/**
 *
 * @author Paul Idrovo
 */
public class Vista extends javax.swing.JFrame {

    private static List<Cubierto> listaCubiertos;
    private static List<JLabel> lblCubiertos;
    private static List<JLabel> lblFilosofos;

    public Vista() {
        initComponents();
        listaCubiertos = new ArrayList<>();
        lblCubiertos = new ArrayList<>();
        lblFilosofos = new ArrayList<>();

        /*
        int numero = 6;
        for (int i = 0; i < numero; i++) {
            listaCubiertos.add(new Cubierto(true));
        }

        lblCubiertos.add(cubierto1);
        lblCubiertos.add(cubierto2);
        lblCubiertos.add(cubierto3);
        lblCubiertos.add(cubierto4);
        lblCubiertos.add(cubierto5);
        lblCubiertos.add(cubierto6);

        lblFilosofos.add(Filosofo1);
        lblFilosofos.add(Filosofo2);
        lblFilosofos.add(Filosofo3);
        lblFilosofos.add(Filosofo4);
        lblFilosofos.add(Filosofo5);
        lblFilosofos.add(Filosofo6);

        new FilosofoHilo(0, listaCubiertos, lblCubiertos, lblFilosofos, 1).start();
        new FilosofoHilo(1, listaCubiertos, lblCubiertos, lblFilosofos, 2).start();
        new FilosofoHilo(2, listaCubiertos, lblCubiertos, lblFilosofos, 3).start();
        new FilosofoHilo(3, listaCubiertos, lblCubiertos, lblFilosofos, 4).start();
        new FilosofoHilo(4, listaCubiertos, lblCubiertos, lblFilosofos, 0).start();

        /*
        Runnable filosofoHilo1 = new FilosofoHilo(0, listaCubiertos, imagenesCubiertos, imagenesFilosofos);
        Runnable filosofoHilo2 = new FilosofoHilo(1, listaCubiertos, imagenesCubiertos, imagenesFilosofos);
        Runnable filosofoHilo3 = new FilosofoHilo(2, listaCubiertos, imagenesCubiertos, imagenesFilosofos);
        Runnable filosofoHilo4 = new FilosofoHilo(3, listaCubiertos, imagenesCubiertos, imagenesFilosofos);
        Runnable filosofoHilo5 = new FilosofoHilo(4, listaCubiertos, imagenesCubiertos, imagenesFilosofos);

          
        
        filosofoHilo1.run();
        filosofoHilo2.run();
        filosofoHilo3.run();
        filosofoHilo4.run();
        filosofoHilo5.run();
         
        new Thread(filosofoHilo1).start();
        new Thread(filosofoHilo2).start();
        new Thread(filosofoHilo3).start();
        new Thread(filosofoHilo4).start();
        new Thread(filosofoHilo5).start();
         */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMesa = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        spnNumeroFilosofos = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlMesa.setMaximumSize(new java.awt.Dimension(700, 700));
        pnlMesa.setMinimumSize(new java.awt.Dimension(700, 700));
        pnlMesa.setPreferredSize(new java.awt.Dimension(700, 700));

        javax.swing.GroupLayout pnlMesaLayout = new javax.swing.GroupLayout(pnlMesa);
        pnlMesa.setLayout(pnlMesaLayout);
        pnlMesaLayout.setHorizontalGroup(
            pnlMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 870, Short.MAX_VALUE)
        );
        pnlMesaLayout.setVerticalGroup(
            pnlMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 709, Short.MAX_VALUE)
        );

        jButton1.setText("INICIAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        spnNumeroFilosofos.setModel(new javax.swing.SpinnerNumberModel(2, 2, null, 1));

        jLabel1.setText("NUMERO DE FILOSOFOS");

        jLabel2.setText("LIBRE");
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 255, 0)));

        jLabel3.setText("PENSANDO");
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(255, 255, 0)));

        jLabel4.setText("COMIENDO");
        jLabel4.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(255, 0, 51)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(pnlMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(jLabel1)
                        .addGap(61, 61, 61)
                        .addComponent(spnNumeroFilosofos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jButton1)
                        .addGap(81, 81, 81)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(spnNumeroFilosofos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)))
                .addGap(17, 17, 17)
                .addComponent(pnlMesa, javax.swing.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        listaCubiertos = new ArrayList<>();
        lblCubiertos = new ArrayList<>();
        lblFilosofos = new ArrayList<>();
        pnlMesa.removeAll();
        JLabel labelMesa = new JLabel("MESA", SwingConstants.CENTER);
        labelMesa.setBounds(100, 100, 500, 500);
        labelMesa.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(153, 51, 0)));
        labelMesa.setFont(new Font("Verdana", Font.BOLD, 30)); //ESTILO TEXTO
        pnlMesa.add(labelMesa);
        int numero = (Integer) spnNumeroFilosofos.getValue();
        boolean imparFilosofos = false;
        int numeroLadoMesa =0;
        if (numero % 2 != 0) {
            imparFilosofos = true;
            numeroLadoMesa = numero -1;
        }else{
            numeroLadoMesa= numero/2;
        }
        int ladoActual = 1;
        int contador = 0;
        boolean cambioLado = false;
        int salto = (int) 500 / numero;
        int posicion = salto*numeroLadoMesa;
        int posicion2 = 610;
        int dimension = 30;
        for (int i = 0; i < numero; i++) {
            contador++;
            JLabel labelFilosofos = new JLabel("F " + (i + 1));            
            switch (ladoActual) {
                case 1:
                    labelFilosofos.setBounds(posicion, posicion2, dimension, dimension);
                    labelFilosofos.setFont(new Font("Verdana", Font.BOLD, 10)); //ESTILO TEXTO
                    pnlMesa.add(labelFilosofos);
                    posicion = posicion - salto;
                    break;

                case 2:
                    if (cambioLado) {
                        posicion = salto*numeroLadoMesa;
                        posicion2 = 10;
                        cambioLado = false;
                    }
                    labelFilosofos.setBounds(posicion2, posicion, dimension, dimension);
                    labelFilosofos.setFont(new Font("Verdana", Font.BOLD, 10)); //ESTILO TEXTO
                    pnlMesa.add(labelFilosofos);
                    posicion = posicion - salto;
                    break;
                case 3:
                    if (cambioLado) {
                        if (imparFilosofos) {
                            salto = (int) 500 / (numero - 1);
                            numeroLadoMesa = numero - 2;
                        }
                        posicion = salto;
                        posicion2 = 70;
                        cambioLado = false;
                    }
                    labelFilosofos.setBounds(posicion, posicion2, dimension, dimension);
                    labelFilosofos.setFont(new Font("Verdana", Font.BOLD, 10)); //ESTILO TEXTO
                    pnlMesa.add(labelFilosofos);
                    posicion = posicion + salto;
                    break;
                case 4:
                    if (cambioLado) {
                        if(imparFilosofos){
                            salto = (int) 500 / (numero-1);
                            numeroLadoMesa = numero - 2;
                        }
                        posicion = salto;
                        posicion2 = 610;
                        cambioLado = false;
                    }
                    labelFilosofos.setBounds(posicion2, posicion, dimension, dimension);
                    labelFilosofos.setFont(new Font("Verdana", Font.BOLD, 10)); //ESTILO TEXTO
                    pnlMesa.add(labelFilosofos);
                    posicion = posicion + salto;
                    break;

            }
            if (contador == numeroLadoMesa) {
                ladoActual++;
                cambioLado = true;
                contador = 0;
            }
            
            contador++;
            JLabel labelCubierto = new JLabel("C " + (i + 1));
            switch (ladoActual) {
                case 1:
                    labelCubierto.setBounds(posicion, posicion2, dimension, dimension);
                    labelCubierto.setFont(new Font("Verdana", Font.BOLD, 10)); //ESTILO TEXTO
                    pnlMesa.add(labelCubierto);
                    posicion = posicion - salto;
                    break;

                case 2:
                    if (cambioLado) {
                        posicion = salto*numeroLadoMesa;
                        posicion2 = 10;
                        cambioLado = false;
                    }
                    labelCubierto.setBounds(posicion2, posicion, dimension, dimension);
                    labelCubierto.setFont(new Font("Verdana", Font.BOLD, 10)); //ESTILO TEXTO
                    pnlMesa.add(labelCubierto);
                    posicion = posicion - salto;
                    break;
                case 3:
                    if (cambioLado) {
                        if (imparFilosofos) {
                            salto = (int) 500 / (numero - 1);
                            numeroLadoMesa = numero - 2;
                        }
                        posicion = salto;
                        posicion2 = 70;
                        cambioLado = false;
                    }
                    labelCubierto.setBounds(posicion, posicion2, dimension, dimension);
                    labelCubierto.setFont(new Font("Verdana", Font.BOLD, 10)); //ESTILO TEXTO
                    pnlMesa.add(labelCubierto);
                    posicion = posicion + salto;
                    break;
                case 4:
                    if (cambioLado) {
                        if(imparFilosofos){
                            salto = (int) 500 / (numero-1);
                            numeroLadoMesa = numero - 2;
                        }
                        posicion = salto;
                        posicion2 = 610;
                        cambioLado = false;
                    }
                    labelCubierto.setBounds(posicion2, posicion, dimension, dimension);
                    labelCubierto.setFont(new Font("Verdana", Font.BOLD, 10)); //ESTILO TEXTO
                    pnlMesa.add(labelCubierto);
                    posicion = posicion + salto;
                    break;

            }
            if (contador == numeroLadoMesa) {
                ladoActual++;
                cambioLado = true;
                contador = 0;
            }
            

            lblCubiertos.add(labelCubierto);
            lblFilosofos.add(labelFilosofos);            
            listaCubiertos.add(new Cubierto(true));
        }
        pnlMesa.updateUI();
        
        for (int i = 0; i < listaCubiertos.size()-1; i++) {
            new FilosofoHilo(i, listaCubiertos, lblCubiertos, lblFilosofos, i+1).start();
        }
         
        /*new FilosofoHilo(0, listaCubiertos, lblCubiertos, lblFilosofos, 1).start();
        new FilosofoHilo(1, listaCubiertos, lblCubiertos, lblFilosofos, 2).start();
        new FilosofoHilo(2, listaCubiertos, lblCubiertos, lblFilosofos, 3).start();
        new FilosofoHilo(3, listaCubiertos, lblCubiertos, lblFilosofos, 4).start();*/
        new FilosofoHilo(listaCubiertos.size()-1, listaCubiertos, lblCubiertos, lblFilosofos, 0).start();
        
        /*
        lblCubiertos.add(cubierto1);
        lblCubiertos.add(cubierto2);
        lblCubiertos.add(cubierto3);
        lblCubiertos.add(cubierto4);
        lblCubiertos.add(cubierto5);
        lblCubiertos.add(cubierto6);

        lblFilosofos.add(Filosofo1);
        lblFilosofos.add(Filosofo2);
        lblFilosofos.add(Filosofo3);
        lblFilosofos.add(Filosofo4);
        lblFilosofos.add(Filosofo5);
        lblFilosofos.add(Filosofo6);

        new FilosofoHilo(0, listaCubiertos, lblCubiertos, lblFilosofos, 1).start();
        new FilosofoHilo(1, listaCubiertos, lblCubiertos, lblFilosofos, 2).start();
        new FilosofoHilo(2, listaCubiertos, lblCubiertos, lblFilosofos, 3).start();
        new FilosofoHilo(3, listaCubiertos, lblCubiertos, lblFilosofos, 4).start();
        new FilosofoHilo(4, listaCubiertos, lblCubiertos, lblFilosofos, 0).start();
         */
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel pnlMesa;
    private javax.swing.JSpinner spnNumeroFilosofos;
    // End of variables declaration//GEN-END:variables
}
